# Generated by Django 4.1.7 on 2024-09-02 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reservation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation_end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay_times', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('is_preorder', models.IntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp_test.customer', verbose_name='顧客ID')),
            ],
        ),
    ]
