# Generated by Django 4.1.7 on 2024-09-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp_test', '0003_rename_name_reservation_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_end_datetime',
            new_name='end_datetime',
        ),
    ]
