# Generated by Django 4.1.7 on 2024-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp_test', '0005_rename_customer_id_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
