# Generated by Django 4.1.7 on 2024-09-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp_test', '0006_reservation_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
    ]
