# Generated by Django 4.1.7 on 2024-09-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0010_remove_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('menus', models.ManyToManyField(to='cafeapp.menu')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.reservation')),
            ],
        ),
    ]
