# Generated by Django 4.1.7 on 2024-09-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp_test', '0011_menuselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='012345678901', max_length=11),
            preserve_default=False,
        ),
    ]
