# Generated by Django 4.1.7 on 2024-10-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp_test', '0012_reservation_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
