# Generated by Django 4.1.7 on 2024-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
