# Generated by Django 4.1.7 on 2024-09-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0002_alter_reservation_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='customer_name',
        ),
    ]
