# Generated by Django 4.1.7 on 2024-09-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0008_category_alter_reservation_is_preorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
